name: Build Luxtorpeda

on:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{ secrets.github_token }}
  build:
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: rust:1.36-stretch
    env:
      CARGO_HOME: ./cargo
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: make release
    - name: Package
      run: make luxtorpeda.tar.xz
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: luxtorpeda.tar.xz
        path: ./luxtorpeda.tar.xz
  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: luxtorpeda.tar.xz
    - name: Upload Package to Bintray
      uses: luxtorpeda-dev/github-action-upload-bintray@v1
      with:
        file: ./luxtorpeda.tar.xz
        file_name: "luxtorpeda-${{ needs.findengine.outputs.build_number }}.tar.xz"
        upload_path: '/'
        api_user: ${{ secrets.BINTRAY_USER }}
        api_key: ${{ secrets.BINTRAY_API_KEY }}
        repository_user: ${{ secrets.BINTRAY_OWNER }}
        repository: ${{ secrets.BINTRAY_REPO }}
        package: luxtorpeda
        version: ${{ needs.findengine.setup.build_number }}
        publish: 1
        calculate_metadata: false
